@startuml
skinparam classAttributeIconSize 0
class Magazzino {
 -articoli: ArrayList
 +Magazzino()
 +aggiungiArticoli():void
 +rimuoviArticoli():void
 +modificaQuantita(int):void
 +ricercaArticolo(string)
 +listaArticoli():void
}

class Articolo {
 -nome: String
 -produttore: Produttore
 -dataProduzione: int
 -descrizione: String
 -quantita: int
 -identificatore: String
 +Articolo
}
@enduml